### ISSUE TITLE
Run (some) example notebooks on travis?

### ISSUE THREAD

**Issue by ceball** [pyviz/datashader#407]
Would you take a PR that runs the example notebooks on travis, or are the examples too big to run on travis? What about a subset? (Or perhaps eventually the notebooks could be modified to take parameters, allowing scaled-down data to be used...)

I mean something like ``jupyter nbconvert example/notebook.ipynb --execute --ExecutePreprocessor.timeout=90 --ExecutePreprocessor.kernel_name=python3 --to html`` for each notebook.

Optionally, the html files could be put on s3 so it's possible to see them, but this is probably not necessary (nbconvert shows which cell gives an error, and the last line of the traceback).

**Comment by jbcrail** [comment]
I think this would be an excellent idea. Since most notebooks use large remote datasets, we'll have to use a smaller subset as you suggested to minimize test run time. I also agree that storing the html on s3 shouldn't be necessary.

The following notebooks are self-contained and auto-generate their data:

* pipeline.ipynb
* plotting_pitfalls.ipynb
* trajectory.ipynb
* tseries.ipynb

Let's try these notebooks first to see how Travis handles them.

**Comment by jbednar** [comment]
I think most of the notebooks should work unmodified with stripped-down test data, though a few might have hardcoded bits that depend on the data size.  It would be nice to store some collection of the stripped down versions for use by Travis and then validate against that continuously.  In the longer run we'll have most of the notebooks built as part of the website, but having this stripped-down set of data will still be useful for regression testing even then.

**Comment by ceball** [comment]
Minor update: we're up to one notebook running on travis+appveyor so far, but getting closer to running more of them with "small" datasets/equivalent.

**Comment by jbednar** [comment]
Smoke tests are now supported, and we'll be moving the topics out to pyviz.org and so won't need separate tiny-data tests.
