### ISSUE TITLE
Conda package is two releases behind

### ISSUE THREAD

**Issue by rabernat** [pyviz/datashader#659]
Only datashader 0.6.6 is available on conda:
https://anaconda.org/conda-forge/datashader
https://github.com/conda-forge/datashader-feedstock

But the package is up to version 0.6.8. This is causing a problem for us in our Pangeo environments, because 0.6.6 is incompatible with the latest dask releases.

**Comment by jbednar** [comment]
Datashader is directly released on to the `pyviz` conda channel, which is up to date because it's all handled by our automated building systems: https://anaconda.org/pyviz/datashader

We do need to make conda-forge update as well, but unfortunately conda-forge doesn't seem to have any way to be fully automated, because it requires a manual PR to the dependency list whenever a dependency changes.  So it inherently drifts out of date until we manually address it.  Suggestions for how to avoid that problem would be welcome; it's very frustrating!

**Comment by rabernat** [comment]
Got it! Sorry for the confusion.

**Comment by ceball** [comment]
Technically, I think the right place to request an updated version on conda-forge is via an issue at https://github.com/conda-forge/datashader-feedstock (or even better, via a PR :) ).

Anyway, I'm now working on this and will soon open a PR on conda-forge (just waiting on some dependencies to build on conda-forge).
