### ISSUE TITLE
Add Proximity Function

### ISSUE THREAD

**Issue by brendancol** [pyviz/datashader#759]
The `datashader.spatial.proximity` function will return a new datashader aggregate (`xarray.DataArray`) containing the distances of all values to a set of pixels present in an input aggregate.  

## Use Cases:
Yellowstone park boundary polygons (`df.RaggedArray`) -> 
canvas.polygon() (`xr.DataArray`) -> 
proximity (`xr.DataArray`) = distance to Yellowstone park (`xr.DataArray`).    

- AND / OR -

Hydrology Network Lines (`df.RaggedArray`) -> 
canvas.line() (`xr.DataArray`) -> 
proximity (`xr.DataArray`) = distance to nearest stream (`xr.DataArray`).

## Usage Idea:

```python
from datashader.spatial import proximity

...

distance_from_yellowstone = proximity(aggregate, distunits='GEO',
                                      maxdist=None, nodata=np.nan)
```

## Implementation

GDAL has a solid implementation here to port and numba-ize:
https://github.com/OSGeo/gdal/blob/master/gdal/alg/gdalproximity.cpp

**Comment by ebo** [comment]
I am interpreting a comment that jbednar made that you are open to reviews and discussions.

In the landscape ecology and statistics literature this is sometimes also called a distance map (probably also called by other terms as well).  There are actually a number of other use cases that would also be of use, and I will write up a couple of scenarios which can be fleshed out as working examples that you might find useful and/or interesting (and would function as functional tests)

As a side note, I am not sure if the GDAL implementation is the best source to reference, but I will try to research potential alternatives.  

For background I worked on a team that published a paper on the behavior of spatial fragmentation metrics a number of years ago (  https://link.springer.com/article/10.1023/A:1007965018633  ) .  The original scientific question was "what is the effect of clear cutting  on the American pine marten.  As part of this work I developed a fragmentation simulator which allowed me to "fragment" a landscape, and controlled for patch size, shape, placement, and frequency distribution.  Calculating a 'distance map' was a primary step.  That said, after the initial work was complete I used the fragmentation simulator to generate simulated Ponderosa Pine forest stem maps based on known life history characteristics (including seed dispersal, fire mortality, distance to roads/trails, and other fun stuff).

One of the potential uses of such a map is to also have a 'mindist' in addition to your 'maxdist'.  This allows the result to function as a spatial search result.  In addition, by adding the ability of setting mindist<0 you can use the exact same algorithm to calculate an 'occupied edge' -- which is quite useful in certain types of environmental simulations.  I know that there are more efficient ways of calculating different types of edges, but I have found it useful in simulations where I needed to bound min<<0 max<<1.

You have not explicitly added distance to point(s), circles, triangles, and other geometric objects, but that might be something of use to add to canvas.

Also to consider are potential use cases for other distance metrics beside Euclidean -- and even within Euclidean distances you might want to return the distance squared (to save calculating the square root).

Last for now...  Do you want to consider 3 or more dimensional datasets?  This starts to get REALLY expensive computationally for non trivial examples, but might be worth it.  That said, once we start dealing with higher dimetionality, it is often more efficient to calculate the distances using modifications of the Delaunay Triangulation algorithm, sub-divisional surfaces, or other non-raster based algorithms.

Let me know when you get some code to test and I will try to break a couple of hours free to give it a poke.  Over the years I've wanted to reimplement the fragmentation simulator, but never made the time to do it -- in part because of the time it would take to write all the underlying infrastructure.

**Comment by brendancol** [comment]
@ebo hey I will have more to look at this week and will ping you when the initial branch / PR is up.  Thanks for these comments above.  I believe 3D is a bit out-of-scope for datashader, but would be happy to explore it.  `mindist` sounds like a easy and nice addition.

**Comment by ebo** [comment]
You are welcome, and I look forward to checking out the code.
